from django.db import models


class Home(models.Model):
    TYPES_OF_HOMES = [
        ('SingleFamily', 'Single'),
        ('VacantResidentialLand', 'Vacant Land'),
        ('Miscellaneous', 'Miscellaneous'),
        ('MultiFamily2To4', 'Multi Family'),
        ('Condominium', 'Condo'),
        ('Apartment', 'Apartment'),
        ('Duplex', 'Duplex')
    ]

    # Generated by Django
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Fileds from csv file
    area_unit = models.TextField(blank=True, null=True, verbose_name='Area Units')
    bathrooms = models.FloatField(blank=True, null=True, verbose_name='Bathrooms')
    bedrooms = models.IntegerField(blank=True, null=True, verbose_name='Bedrooms')
    home_size = models.IntegerField(blank=True, null=True, verbose_name='Size of House')
    home_type = models.CharField(blank=True, null=True, max_length=100, choices=TYPES_OF_HOMES, verbose_name='Type of Home')
    last_sold_date = models.DateField(blank=True, null=True, verbose_name='Date Last Sold')
    last_sold_price = models.IntegerField(blank=True, null=True, verbose_name='Price Last Sold')
    link = models.URLField(blank=True, verbose_name='Link')
    price = models.IntegerField(blank=True, null=True, verbose_name='Price $')
    property_size = models.IntegerField(blank=True, null=True, verbose_name='Property Size')
    rent_price = models.IntegerField(blank=True, null=True, verbose_name='Rent Price')
    rentzestimate_amount = models.IntegerField(blank=True, null=True, verbose_name='Zillow Estimate Rent Price')
    rentzestimate_last_updated = models.DateField(blank=True, null=True, verbose_name='Zillow Rent Last Updated')
    tax_value = models.FloatField(blank=True, null=True, verbose_name='Tax Value')
    tax_year = models.IntegerField(blank=True, null=True, verbose_name='Tax Year')
    year_built = models.IntegerField(blank=True, null=True, verbose_name='Year Built')
    zestimate_amount = models.IntegerField(blank=True, null=True, verbose_name='Zillow Price Estimate')
    zestimate_last_updated = models.DateField(blank=True, null=True, verbose_name='Zillow Price Last Updated')
    zillow_id = models.IntegerField(unique=True, null=True, blank=True, verbose_name='Zillow ID')
    address = models.TextField(blank=True, verbose_name='Address')
    city = models.TextField(blank=True, verbose_name='City')
    state = models.TextField(blank=True, verbose_name='State')
    zipcode = models.CharField(blank=True, max_length=5, verbose_name='Zip Code')
