# Generated by Django 3.0.8 on 2020-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='area_unit',
            field=models.TextField(blank=True, verbose_name='Area Units'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size of House'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_type',
            field=models.CharField(blank=True, choices=[('SingleFamily', 'Single'), ('VacantResidentialLand', 'Vacant Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Multi Family'), ('Condominium', 'Condo'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex')], max_length=100, null=True, verbose_name='Type of Home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Last Sold'),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_sold_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price Last Sold'),
        ),
        migrations.AlterField(
            model_name='home',
            name='rentzestimate_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zillow Estimate Rent Price'),
        ),
        migrations.AlterField(
            model_name='home',
            name='rentzestimate_last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Zillow Rent Last Updated'),
        ),
        migrations.AlterField(
            model_name='home',
            name='zestimate_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zillow Price Estimate'),
        ),
        migrations.AlterField(
            model_name='home',
            name='zestimate_last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Zillow Price Last Updated'),
        ),
    ]
