# Generated by Django 3.0.8 on 2020-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housefinder', '0002_auto_20200726_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='area_unit',
            field=models.TextField(blank=True, null=True, verbose_name='Area Units'),
        ),
    ]
